routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('auth.login');
});







Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Agent
Route::resource('agent','agentController');
//customer
Route::resource('customer','customerController');
//Supervisor
Route::resource('supervisor','supervisorController');
//City
Route::resource('city','cityController');
//Slider
Route::get('slider','SliderController@create')->name('slider.create');
Route::get('slider/all','SliderController@index')->name('slider.index');
Route::post('slider','SliderController@store')->name('slider.store');
Route::get('slider/{id}','SliderController@edit')->name('slider.edit');
Route::post('slider/{id}','SliderController@update')->name('slider.update');

//area
Route::resource('area','areaController');
//notification
Route::resource('notification','notificationController');
//services
Route::resource('services','servicesController');
//Sub services
Route::resource('subservices','subservicesController');
//FAQS
Route::resource('faqs','FaqsController');

Route::get('supervisor/assigned-kamay-to-supervisor/{id}','supervisorController@getAssignedKamayToSupervisor')->name('supervisor.assigned-kamay-to-supervisor');

//Badges
Route::resource('badges','BadgeController');

//Person Badges
Route::resource('assign-badges','PerBadgeController');
Route::post('get-badges-by-user','PerBadgeController@getBadgesByUser');

//Kamay Worker
Route::resource('kama','kamaController');
Route::get('/worker-growth-potential', 'kamaGrowthController@kamaGrowth')->name('worker-growth-potential');
Route::get('/kamayview', 'kamaController@kamayView')->name('kamayview');
Route::get('/final-approval-kamay', 'kamaController@getFinalApprovalKamay')->name('final-approval-kamay');
Route::get('/assigned-kamay', 'kamaController@getAssignedKamay')->name('assigned-kamay');
Route::get('/kamayrequest', 'kamaController@kamayRequest')->name('kamayrequest');
Route::post('get-area-by-city','kamaController@getArea');
Route::post('get-area-by-cityname','kamaController@getAreaByCityName');
Route::post('/assign-supervisor','kamaController@assignSupervisor')->name('assign-supervisor');
Route::post('/final-approval/{id}','kamaController@finalApproval')->name('final-approval');
Route::get('/view-approved-worker', 'kamaController@getApprovedWorker')->name('view-approved-worker');
Route::get('/assigned-supervisor-list/{kama_id}','kamaController@supervisorAssignedList')->name('assigned-supervisor-list');

//Jobs
Route::resource('jobs','jobsController');
Route::get('/view-inprogress', 'jobsController@getInprogress')->name('jobs.view-inprogress');
Route::get('/view-cancelled', 'jobsController@getCancelled')->name('jobs.view-cancelled');
Route::get('/view-unassigned', 'jobsController@getUnassigned')->name('jobs.view-unassigned');
Route::get('/view-completed', 'jobsController@getCompleted')->name('jobs.view-completed');
Route::get('/view-onhold', 'jobsController@getOnHold')->name('jobs.view-nohold');
Route::get('/view-scheduled', 'jobsController@getScheduled')->name('jobs.view-scheduled');
Route::get('/all-jobs', 'jobsController@getAllJobs')->name('jobs.all-jobs');
Route::get('/jobs-report', 'jobsController@getJobsReport')->name('jobs.jobs-report');
Route::post('/jobs-report-range', 'jobsController@getJobsReportRange')->name('jobs.jobs-report-range');
Route::get('/today-jobs', 'jobsController@getTodayJobs')->name('jobs.today-jobs');
// Route::post('seller/update_store_slider','API\SellerController@updateSlider');
Route::get('/assigned-job-view/{order_id}','jobsController@viewAssginedJobs')->name('jobs.assigned-job-view');
Route::get('/schedule-details/{order_id}','jobsController@getScheduleDetails')->name('jobs.schedule-details');
Route::post('/unassigned-job-submit','jobsController@unassignedJobSubmit')->name('unassigned-job-submit');
//Panic
Route::get('/panic-reported', 'panicController@getPanicReported')->name('panic.panic-reported');
Route::get('/panic-resolved', 'panicController@getPanicResolved')->name('panic.panic-resolved');
Route::resource('panic','panicController');

Route::get('/request/orders', 'RequestController@index')->name('admin.request.order');

Route::get('/payment', 'PaymentController@index')->name('admin.payment');
Route::post('/payment/{id}', 'PaymentController@update')->name('admin.payment.update');

Route::get('/fmc','notificationController@sendNotification');
Route::get('/send-notification/{test}/{id}','notificationController@checkSendNotification')->name('send-notification');

Route::get('/user/notf/show', 'notificationController@user_notf_show')->name('user-notf-show');
Route::get('/user/final/approval/show', 'notificationController@final_approval_notf_show')->name('final-approval-notf-show');
Route::get('/user/panic/show', 'notificationController@panic_notf_show')->name('panic-notf-show');

Route::resource('share','ShareController');

Route::post('/save-token', 'notificationController@saveToken')->name('save-token');

/* BULK MESSAGE */
Route::get('/bulk/message/', 'BulkMessageController@index')->name('bulk.message');
Route::post('/bulk/message/send', 'BulkMessageController@send')->name('bulk.message.send');
Route::post('/bulk/message/service', 'BulkMessageController@service')->name('bulk.message.with.service');

Route::post('get-user-by-role','BulkMessageController@getUserByRole');

/* SCHEDULE TIME COUNT */
Route::get('/schedule', 'ScheduleController@index')->name('schedule.index');
Route::post('/schedule/{id}', 'ScheduleController@update')->name('schedule.update');

Route::get('/no-service-charges', 'servicesController@noServiceCharges')->name('no.service.charges');
Route::post('/no-service-charges', 'servicesController@noServiceChargesUpdate')->name('no.service.charges.update');

//Update Status
Route::post('/job/status/updated/{id}', 'jobsController@statusUpdate')->name('update.status');

app/area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class area extends Model
{
    protected $table = 'area_manage';
    protected $fillable = ['area_name','status'];
}

app/Http/Controllers/areaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\territory;
use App\personInfo;
use App\City;
use App\Services;
use DB;
use Validator;
use File;
use Auth;
use App\Users;
use App\KamaTerritory;
use App\area;


class areaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 

    public function index()
    {
        //$data = area::all();
        $data = area::join('territory', 'area_manage.terr_id', '=', 'territory.terr_id')
                ->select('territory.name as territory_name','area_manage.id','area_manage.status')
               ->get();
               // dd($data);die();     
			return view('area.index', compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $cityData = City::where('status', 1)->get();
        $expertise = Services::where('parent_id', 0)->where('s_id', '!=', 1)->get();
        $data = territory::all();
        // dd($data);die();
        return view('area.create', compact('cityData','expertise','data'));
    	
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(Request $request)
    {

        
        $request->validate([
            'terr_id'    =>  'required',
            'status' => 'required'
           
           
        ]);
        // print_r($request->all() );exit();

        
        $area = new area();
        $area->terr_id = $request->input('terr_id');
        $area->status = $request->input('status');
        $area->save();

       

       
        return redirect('area')->with('success', 'Data Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
             $cityData = City::where('status', 1)->get();
             $data = area::where('id', $id)->first();
             $territory = territory::all();
             // dd($data);die();
            

            return view('area.edit', compact('cityData','data','territory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

         
        $request->validate([
             'terr_id'    =>  'required',
            'status' => 'required'
           
           
        ]);
        // print_r($request->all() );
       // dd($request->input('area'));exit();

            
            $area = area::find($id);

            $area->terr_id = $request->input('terr_id');
            $area->status = $request->input('status');

            $area->save();
       
        return redirect('area/'.$id.'/edit')->with('success', 'Data updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }




}

resources/views/area/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">Add Area</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a>
                    </li>
                    <li class="breadcrumb-item active">Add Area
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="content-body">
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="basic-layout-form">Area Details</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <form class="form" action="{{route('area.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf   
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="services">Select Area</label>
                                                <select class="form-control" name="terr_id">
                                                    @foreach($data as $area)                
                                                    <option value="{{$area->terr_id}}">{{$area->name}}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="projectinput1">Select Status</label>
                                                <select name="status" id="status" class="form-control select2" >
                                                    <option value="1">Block</option>
                                                    <option value="0">Unblock</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions text-right">
                                    <button type="submit" class="btn btn-primary">
                                    <i class="la la-check-square-o"></i> Save
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
               <div class="card">
                  <div class="card-header">
                     <h4 class="card-title" id="basic-layout-colored-form-control">Information</h4>
                     <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                     <div class="heading-elements">
                        <ul class="list-inline mb-0">
                           <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                           <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                           <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                           <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="card-content collapse show">
                     <div class="card-body pt-0">
                        @if($errors->any())
                        <div class="alert alert-danger">
                           <ul>
                              @foreach($errors->all() as $error)
                              <li>{{ $error }}</li>
                              @endforeach
                           </ul>
                        </div>
                        @endif
                        @if (\Session::has('error'))
                        <div class="alert alert-danger">
                           <ul>
                              <li>{!! \Session::get('error') !!}</li>
                           </ul>
                        </div>
                        @endif
                        @if (\Session::has('success'))
                        <div class="alert alert-success">
                           <ul>
                              <li>{!! \Session::get('success') !!}</li>
                           </ul>
                        </div>
                        @endif
                     </div>
                  </div>
               </div>
            </div>
        </div>
    </section>
</div>
@stop
@section('script')
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>
<script type="text/javascript">
    $(":input").inputmask();
    $('#terr_id').select2();
</script>
@endsection

resources/views/area/edit.blade.php
@extends('layouts.admin')
   @push('styles')
    <style>
        .pac-container {
            z-index: 9999999 !important;
            top: 65px !important;
            left: 15px !important;
        }
        #address-input::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
            color: red;
            opacity: 1; /* Firefox */
        }

        #address-input:-ms-input-placeholder { /* Internet Explorer 10-11 */
            color: red;
        }

        #address-input::-ms-input-placeholder { /* Microsoft Edge */
            color: red;
        }
    </style>
@endpush
@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">Edit area</h3>
            <div class="row breadcrumbs-top d-inline-block">
              <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a>
                  </li>
<!--                   <li class="breadcrumb-item active">Create Booking
                  </li> -->
                </ol>
              </div>
            </div>
        </div>
    </div>
    @if($errors->any())
        <div class="alert alert-danger">
         <ul>
          @foreach($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
         </ul>
        </div>
        @endif

         @if($message = Session::get('success'))
          <div class="alert alert-success">
            <p>{{$message}}</p>
          </div>
        @endif
    <div class="content-body">
        <section id="basic-form-layouts">
            <div class="row match-height">
             <div class="col-md-12">
                <div class="card">
                   <div class="card-header">
                      <h4 class="card-title" id="basic-layout-form">area Update</h4>
                      <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                      <div class="heading-elements">
                         <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                         </ul>
                      </div>
                   </div>
                   <div class="card-content collapse show">
                      
                        <div class="card-body">
                        <form class="form" action="{{route('area.update',$data->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')  
                            <div class="form-body">
                               <div class="row">
                                <div class="col-md-6">
                                     <div class="form-group">
                                      <label for="services">Select Area</label>
                                          <select class="form-control" name="terr_id">
                                             @foreach($territory as $area)
                                            <option value="{{$area->terr_id}}" {{  $area->terr_id ==  $data->terr_id ? 'selected' : ''  }}>{{$area->name}}
                                            </option>
                                            @endforeach
                                          </select>
                                     </div>
                                  </div>
                                 

                                  <div class="col-md-6">
                                     <div class="form-group">
                                        <label for="projectinput1">Select Status</label>
                                       <select name="status" id="status" class="form-control" >
                                       
                                          <option value="">Select Status</option>
                                          <option value="1" {{  $data->status == 1 ? 'selected' : ''  }}>Block</option>
                                          <option value="0" {{  $data->status == 0 ? 'selected' : ''  }}>Unblock</option>   
                                        
                                      </select>     
                                     </div>
                                  </div>

                              </div>
                            </div> 
                            <div class="form-actions text-right">
                               <button type="submit" class="btn btn-primary">
                               <i class="la la-check-square-o"></i> Save
                               </button>
                            </div>
                         </form>
                      </div>
                   </div>
                </div>
             </div>
            
          </div>
       </section>
      
</div>

@stop

@section('script')
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>
<script type="text/javascript">
    $(":input").inputmask();
</script>
<script src="//maps.googleapis.com/maps/api/js?key=AIzaSyAggB51ZRomTQ28c6SIlT0Zkjtd2boQ3V0&libraries=places&callback=initialize" async defer></script>
<script>
    var get_city = {!! json_encode($cityData->toArray()) !!};
    function initialize() {
    
      $('form').on('keyup keypress', function(e) {
        var keyCode = e.keyCode || e.which;
        if (keyCode === 13) {
          e.preventDefault();
          return false;
        }
      });
      const locationInputs = document.getElementsByClassName("map-input");
    
      const autocompletes = [];
      const geocoder = new google.maps.Geocoder;
      for (let i = 0; i < locationInputs.length; i++) {
    
        const input = locationInputs[i];
        const fieldKey = input.id.replace("-input", "");
        const isEdit = document.getElementById(fieldKey + "-latitude").value != '' && document.getElementById(fieldKey + "-longitude").value != '';
    
        const latitude = parseFloat(document.getElementById(fieldKey + "-latitude").value) || -33.8688;
        const longitude = parseFloat(document.getElementById(fieldKey + "-longitude").value) || 151.2195;
    
        const map = new google.maps.Map(document.getElementById(fieldKey + '-map'), {
          center: {lat: latitude, lng: longitude},
          zoom: 13
        });
      console.log(map);
        const marker = new google.maps.Marker({
          map: map,
          position: {lat: latitude, lng: longitude},
        });
    
        marker.setVisible(isEdit);
    
        const autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.key = fieldKey;
        autocompletes.push({input: input, map: map, marker: marker, autocomplete: autocomplete});
      }
    
      for (let i = 0; i < autocompletes.length; i++) {
        const input = autocompletes[i].input;
        const autocomplete = autocompletes[i].autocomplete;
        const map = autocompletes[i].map;
        const marker = autocompletes[i].marker;
    
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
          marker.setVisible(false);
          const place = autocomplete.getPlace();
    
          geocoder.geocode({'placeId': place.place_id}, function (results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
              const lat = results[0].geometry.location.lat();
            const lng = results[0].geometry.location.lng();
                        var sublocality;
            for (var i = 0; i < results[0].address_components.length; i++) {
              if (results[0].address_components[i].types[0] == "locality") {
                //this is the object you are looking for City
                city = results[0].address_components[i];
              }
                            var component = results[0].address_components[i];
                            if (!sublocality && component.types.indexOf("sublocality_level_1") > -1){
                                sublocality = component.long_name;
                            }
                        }
                    
                        var checker = 0;
                        for(var i = 0; i < get_city.length; i++){
                            if(get_city[i].name == city.long_name){
                                checker = 1;
                            }
                        }
            if(checker == 1){
                            setLocationCoordinates(autocomplete.key, lat, lng, city, sublocality);
                            $('#address-input').removeClass('error');
            }else{
              $('#address-input').attr('placeholder','Sorry, Right Now, we are not Operational in this City');
                            $('#address-input').val('');
              $('#address-latitude').val('0');
              $('#address-longitude').val('0');
              $('#address-input').addClass('error');
              $('#address-city').val('');
                            $('#selected_city').val('')
                            $('#selected_terr').html('')
            }
            }
          });
    
          if (!place.geometry) {
            window.alert("No details available for input: '" + place.name + "'");
            input.value = "";
            return;
          }
    
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);
    
        });
      }
      }
    
      function setLocationCoordinates(key, lat, lng, city, sublocality) {
      const latitudeField = document.getElementById(key + "-" + "latitude");
      const longitudeField = document.getElementById(key + "-" + "longitude");
      const cityField = document.getElementById(key + "-" + "city");
            const areaField = document.getElementById(key + "-" + "area");
            const selectedCityField = document.getElementById("selected_city");
      latitudeField.value = lat;
      longitudeField.value = lng;
      cityField.value = city.long_name;
            areaField.value = sublocality;
            selectedCityField.value = city.long_name;
            $.ajax({
                url: "{{url('get-area-by-cityname')}}",
                type: "POST",
                data: {
                    city_id: city.long_name,
                    _token: '{{csrf_token()}}'
                },
                dataType: 'json',
                success: function(result) {
                    console.log(result);
                    $.each(result.area, function(key, value) {
                        $("#selected_area").append('<option value="' + value.terr_id + '">' + value.name + '</option>');
                        $("#selected_terr").append('<option value="' + value.terr_id + '">' + value.name + '</option>');
                    });
                    //$('#city').html('<option value="">Select City First</option>');
                }
            });
    }
    
    var addressInputElement = $('#address-input');
      addressInputElement.on('focus', function () {
      var pacContainer = $('.pac-container');
      $(addressInputElement.parent()).append(pacContainer);
    })

    $(document).ready(function () {
      $('#nav-reg11 .mregisterform input[type=file]').change(function () {
        $('#btnUpload').show();
        $('#divFiles').html('');
        for (var i = 0; i < this.files.length; i++) {
          console.log(URL.createObjectURL(this.files[i]));
          var fileId = i;
          $("#divFiles").append('<li>' +
                      '<img src="' + URL.createObjectURL(this.files[i]) + '">' +
                    '</li>');
        }
      })
    });
  </script>
@endsection

resources/views/area/index.blade.php
@extends('layouts.admin')
   
@section('content')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">My Area</h3>
            <div class="row breadcrumbs-top d-inline-block">
              <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Area
                  </li>
                </ol>
              </div>
            </div>
        </div>
    </div>
    
         @if($message = Session::get('success'))
	        <div class="alert alert-success">
	        	<p>{{$message}}</p>
	        </div>
         @endif
        
        
   <div class="row">


          <div id="recent-sales" class="col-12 col-md-12">

            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Area List</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                
              </div>
              <div class="card-content mt-1">
                <div class="table-responsive" style="padding: 2%;">
                  <table class="table table-striped table-bordered zero-configuration">
                    <thead>
                     	<tr>
		                  	<th>ID</th>
		                    <th>Area</th>
		                   	<th>Status</th>
		                   	<!-- <th>Action</th> -->
		                </tr>
                    </thead>
                    <tbody>
                       @foreach($data as $area)
                       <tr>
                        <td class="text-truncate">{{$area->id}}</td>
                          <td class="text-truncate">{{$area->territory_name}}</td>
                          <!-- <td class="text-truncate">{{$area->status}}</td> -->
                          <td align="center"> 
                            <div class="fonticon-wrap">
                                <a href="{{ route('area.edit', $area->id) }}"><i class="ft-edit"></i></a>
                            </div>
                          </td>

	               		
                         
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

@push('scripts')

@endpush