routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('auth.login');
});







Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Agent
Route::resource('agent','agentController');
//customer
Route::resource('customer','customerController');
//Supervisor
Route::resource('supervisor','supervisorController');
//City
Route::resource('city','cityController');
//Slider
Route::get('slider','SliderController@create')->name('slider.create');
Route::get('slider/all','SliderController@index')->name('slider.index');
Route::post('slider','SliderController@store')->name('slider.store');
Route::get('slider/{id}','SliderController@edit')->name('slider.edit');
Route::post('slider/{id}','SliderController@update')->name('slider.update');

//area
Route::resource('area','areaController');
//notification
Route::resource('notification','notificationController');
//services
Route::resource('services','servicesController');
//Sub services
Route::resource('subservices','subservicesController');
//FAQS
Route::resource('faqs','FaqsController');

Route::get('supervisor/assigned-kamay-to-supervisor/{id}','supervisorController@getAssignedKamayToSupervisor')->name('supervisor.assigned-kamay-to-supervisor');

//Badges
Route::resource('badges','BadgeController');

//Person Badges
Route::resource('assign-badges','PerBadgeController');
Route::post('get-badges-by-user','PerBadgeController@getBadgesByUser');

//Kamay Worker
Route::resource('kama','kamaController');
Route::get('/worker-growth-potential', 'kamaGrowthController@kamaGrowth')->name('worker-growth-potential');
Route::get('/kamayview', 'kamaController@kamayView')->name('kamayview');
Route::get('/final-approval-kamay', 'kamaController@getFinalApprovalKamay')->name('final-approval-kamay');
Route::get('/assigned-kamay', 'kamaController@getAssignedKamay')->name('assigned-kamay');
Route::get('/kamayrequest', 'kamaController@kamayRequest')->name('kamayrequest');
Route::post('get-area-by-city','kamaController@getArea');
Route::post('get-area-by-cityname','kamaController@getAreaByCityName');
Route::post('/assign-supervisor','kamaController@assignSupervisor')->name('assign-supervisor');
Route::post('/final-approval/{id}','kamaController@finalApproval')->name('final-approval');
Route::get('/view-approved-worker', 'kamaController@getApprovedWorker')->name('view-approved-worker');
Route::get('/assigned-supervisor-list/{kama_id}','kamaController@supervisorAssignedList')->name('assigned-supervisor-list');

//Jobs
Route::resource('jobs','jobsController');
Route::get('/view-inprogress', 'jobsController@getInprogress')->name('jobs.view-inprogress');
Route::get('/view-cancelled', 'jobsController@getCancelled')->name('jobs.view-cancelled');
Route::get('/view-unassigned', 'jobsController@getUnassigned')->name('jobs.view-unassigned');
Route::get('/view-completed', 'jobsController@getCompleted')->name('jobs.view-completed');
Route::get('/view-onhold', 'jobsController@getOnHold')->name('jobs.view-nohold');
Route::get('/view-scheduled', 'jobsController@getScheduled')->name('jobs.view-scheduled');
Route::get('/all-jobs', 'jobsController@getAllJobs')->name('jobs.all-jobs');
Route::get('/jobs-report', 'jobsController@getJobsReport')->name('jobs.jobs-report');
Route::post('/jobs-report-range', 'jobsController@getJobsReportRange')->name('jobs.jobs-report-range');
Route::get('/today-jobs', 'jobsController@getTodayJobs')->name('jobs.today-jobs');
// Route::post('seller/update_store_slider','API\SellerController@updateSlider');
Route::get('/assigned-job-view/{order_id}','jobsController@viewAssginedJobs')->name('jobs.assigned-job-view');
Route::get('/schedule-details/{order_id}','jobsController@getScheduleDetails')->name('jobs.schedule-details');
Route::post('/unassigned-job-submit','jobsController@unassignedJobSubmit')->name('unassigned-job-submit');
//Panic
Route::get('/panic-reported', 'panicController@getPanicReported')->name('panic.panic-reported');
Route::get('/panic-resolved', 'panicController@getPanicResolved')->name('panic.panic-resolved');
Route::resource('panic','panicController');

Route::get('/request/orders', 'RequestController@index')->name('admin.request.order');

Route::get('/payment', 'PaymentController@index')->name('admin.payment');
Route::post('/payment/{id}', 'PaymentController@update')->name('admin.payment.update');

Route::get('/fmc','notificationController@sendNotification');
Route::get('/send-notification/{test}/{id}','notificationController@checkSendNotification')->name('send-notification');

Route::get('/user/notf/show', 'notificationController@user_notf_show')->name('user-notf-show');
Route::get('/user/final/approval/show', 'notificationController@final_approval_notf_show')->name('final-approval-notf-show');
Route::get('/user/panic/show', 'notificationController@panic_notf_show')->name('panic-notf-show');

Route::resource('share','ShareController');

Route::post('/save-token', 'notificationController@saveToken')->name('save-token');

/* BULK MESSAGE */
Route::get('/bulk/message/', 'BulkMessageController@index')->name('bulk.message');
Route::post('/bulk/message/send', 'BulkMessageController@send')->name('bulk.message.send');
Route::post('/bulk/message/service', 'BulkMessageController@service')->name('bulk.message.with.service');

Route::post('get-user-by-role','BulkMessageController@getUserByRole');

/* SCHEDULE TIME COUNT */
Route::get('/schedule', 'ScheduleController@index')->name('schedule.index');
Route::post('/schedule/{id}', 'ScheduleController@update')->name('schedule.update');

Route::get('/no-service-charges', 'servicesController@noServiceCharges')->name('no.service.charges');
Route::post('/no-service-charges', 'servicesController@noServiceChargesUpdate')->name('no.service.charges.update');

//Update Status
Route::post('/job/status/updated/{id}', 'jobsController@statusUpdate')->name('update.status');

app/Http/Controllers/agentController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\territory;
use App\personInfo;
use DB;
use Validator;
use Auth;
class agentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 

    public function index()
    {
        $data = db::table('call_center_agent')->select('*')->get();
                    

                 return view('agent.index', compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

         $cityData = DB::table('city')->select('city_id','name')->get();
        

        return view('agent.create', compact('cityData'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        
        $request->validate([
            'name'      =>  'required',
            'email'     => 'required|string|email|max:255',
            'password'  => 'required|string|min:8|confirmed',
            'role_name'  => 'required',
           
        ]);
        //return $request;exit();
        DB::table('call_center_agent')->insert([
                'name'              => $request->input('name'),
                'email'                 => $request->input('email'),
                'role'                  => $request->input('role_name'),
                'password'              => Hash::make($request->input('password'))
        ]);

        

       
        return redirect('agent')->with('success', 'Data Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = db::table('call_center_agent')->select('*')->where('id',$id)->get();

            return view('agent.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $request->validate([
            'name'      =>  'required',
            'email'     => 'required|string|email|max:255',
            'role_name'  => 'required',
           
        ]);

            
            
        $form_data = array(
               'name'                   => $request->input('name'),
                'email'                 => $request->input('email'),
                'role'                  => $request->input('role_name'),
                'password'              => Hash::make($request->input('password'))
        );

        $perinfo = db::table('call_center_agent')->where('id',$id)->update($form_data);
        
       
        return redirect('agent')->with('success', 'Data updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/agent/create.blade.php
@extends('layouts.admin')
   
@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">Add Agent</h3>
            <div class="row breadcrumbs-top d-inline-block">
              <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a>
                  </li>
<!--                   <li class="breadcrumb-item active">Create Booking
                  </li> -->
                </ol>
              </div>
            </div>
        </div>
    </div>
    @if($errors->any())
        <div class="alert alert-danger">
         <ul>
          @foreach($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
         </ul>
        </div>
        @endif
    <div class="content-body">
        <section id="basic-form-layouts">
            <div class="row match-height">
             <div class="col-md-12">
                <div class="card">
                   <div class="card-header">
                      <h4 class="card-title" id="basic-layout-form">agent Details</h4>
                      <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                      <div class="heading-elements">
                         <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                         </ul>
                      </div>
                   </div>
                   <div class="card-content collapse show">
                      <div class="card-body">
                        <form class="form" action="{{route('agent.store')}}" method="POST" enctype="multipart/form-data" id="booking_form">
                            @csrf 

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input  type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input  type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input  type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>
                        

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Role') }}</label>

                            <div class="col-md-6">
                                <select class="hide-search form-control select2-hidden-accessible" name="role_name" id="hide_search" data-select2-id="hide_search" tabindex="-1" aria-hidden="true" required>
                               <option value="">Select Role</option>
                               <option value="admin" data-select2-id="863">Admin</option>
                                <option value="agent" data-select2-id="864">Agent</option>
                            </select>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                      </div>
                   </div>
                </div>
             </div>
            
          </div>
       </section>
      
</div>

@stop

@section('script')
 


@endsection

resources/views/agent/edit.blade.php
@extends('layouts.admin')
   
@section('content')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">Add Agent</h3>
            <div class="row breadcrumbs-top d-inline-block">
              <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a>
                  </li>
<!--                   <li class="breadcrumb-item active">Create Booking
                  </li> -->
                </ol>
              </div>
            </div>
        </div>
    </div>
    @if($errors->any())
        <div class="alert alert-danger">
         <ul>
          @foreach($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
         </ul>
        </div>
        @endif
    <div class="content-body">
        <section id="basic-form-layouts">
            <div class="row match-height">
             <div class="col-md-12">
                <div class="card">
                   <div class="card-header">
                      <h4 class="card-title" id="basic-layout-form">agent Details</h4>
                      <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                      <div class="heading-elements">
                         <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                            <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                            <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            <li><a data-action="close"><i class="ft-x"></i></a></li>
                         </ul>
                      </div>
                   </div>
                   <div class="card-content collapse show">
                      <div class="card-body">
                        <form class="form" action="{{route('agent.update',$data[0]->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')  
                          <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input  type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{$data[0]->name}}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input  type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{$data[0]->email}}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('New Password') }}</label>

                            <div class="col-md-6">
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" value="" autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input  type="password" value="" class="form-control" name="password_confirmation"  autocomplete="new-password">
                            </div>
                        </div>
                        

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Role') }}</label>

                            <div class="col-md-6">
                                <select class="hide-search form-control select2-hidden-accessible" name="role_name" id="hide_search" data-select2-id="hide_search" tabindex="-1" aria-hidden="true" required>
                               <option value="">Select Role</option>
                               <option value="admin" data-select2-id="863">Admin</option>
                                <option value="agent" data-select2-id="864">Agent</option>
                            </select>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>
                      </div>
                   </div>
                </div>
             </div>
            
          </div>
       </section>
      
</div>

@stop

@section('script')
 


@endsection

resources/views/agent/index.blade.php
@extends('layouts.admin')
   
@section('content')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">My Supervisors</h3>
            <div class="row breadcrumbs-top d-inline-block">
              <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a>
                  </li>
                  <li class="breadcrumb-item active">Supervisors
                  </li>
                </ol>
              </div>
            </div>
        </div>
    </div>
    
         @if($message = Session::get('success'))
	        <div class="alert alert-success">
	        	<p>{{$message}}</p>
	        </div>
         @endif
        
        
   <div class="row">


          <div id="recent-sales" class="col-12 col-md-12">

            <div class="card">
              <div class="card-header">
                <h4 class="card-title">Agent List</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                
              </div>
              <div class="card-content mt-1">
                <div class="table-responsive" style="padding: 2%;">
                  <table class="table table-striped table-bordered zero-configuration">
                    <thead>
                     	<tr>
		                  	<th>Agent ID</th>
		                    <th>Name</th>
		                   	<th>Email</th>
		                   	<th>Role</th>
		                   	<th>Action</th>
		                </tr>
                    </thead>
                    <tbody>
                       @foreach($data as $agent)
                       <tr>
                        <td class="text-truncate">{{$agent->id}}</td>
                          <td class="text-truncate">{{$agent->name}}</td>
                          <td class="text-truncate">{{$agent->email}}</td>
                          <td class="text-truncate">{{$agent->role}}</td>
                    <td>
	               		<div class="buy-now"><a href="{{ route('agent.edit', $agent->id) }}" class="btn btn-info btn-glow round px-1" style="  padding: 0.5rem 0.5rem; font-size: 0.5rem;">Edit Profile</a></div>
	               		</td>
                         
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
@endsection

@push('scripts')

@endpush