routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('auth.login');
});







Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Agent
Route::resource('agent','agentController');
//customer
Route::resource('customer','customerController');
//Supervisor
Route::resource('supervisor','supervisorController');
//City
Route::resource('city','cityController');
//Slider
Route::get('slider','SliderController@create')->name('slider.create');
Route::get('slider/all','SliderController@index')->name('slider.index');
Route::post('slider','SliderController@store')->name('slider.store');
Route::get('slider/{id}','SliderController@edit')->name('slider.edit');
Route::post('slider/{id}','SliderController@update')->name('slider.update');

//area
Route::resource('area','areaController');
//notification
Route::resource('notification','notificationController');
//services
Route::resource('services','servicesController');
//Sub services
Route::resource('subservices','subservicesController');
//FAQS
Route::resource('faqs','FaqsController');

Route::get('supervisor/assigned-kamay-to-supervisor/{id}','supervisorController@getAssignedKamayToSupervisor')->name('supervisor.assigned-kamay-to-supervisor');

//Badges
Route::resource('badges','BadgeController');

//Person Badges
Route::resource('assign-badges','PerBadgeController');
Route::post('get-badges-by-user','PerBadgeController@getBadgesByUser');

//Kamay Worker
Route::resource('kama','kamaController');
Route::get('/worker-growth-potential', 'kamaGrowthController@kamaGrowth')->name('worker-growth-potential');
Route::get('/kamayview', 'kamaController@kamayView')->name('kamayview');
Route::get('/final-approval-kamay', 'kamaController@getFinalApprovalKamay')->name('final-approval-kamay');
Route::get('/assigned-kamay', 'kamaController@getAssignedKamay')->name('assigned-kamay');
Route::get('/kamayrequest', 'kamaController@kamayRequest')->name('kamayrequest');
Route::post('get-area-by-city','kamaController@getArea');
Route::post('get-area-by-cityname','kamaController@getAreaByCityName');
Route::post('/assign-supervisor','kamaController@assignSupervisor')->name('assign-supervisor');
Route::post('/final-approval/{id}','kamaController@finalApproval')->name('final-approval');
Route::get('/view-approved-worker', 'kamaController@getApprovedWorker')->name('view-approved-worker');
Route::get('/assigned-supervisor-list/{kama_id}','kamaController@supervisorAssignedList')->name('assigned-supervisor-list');

//Jobs
Route::resource('jobs','jobsController');
Route::get('/view-inprogress', 'jobsController@getInprogress')->name('jobs.view-inprogress');
Route::get('/view-cancelled', 'jobsController@getCancelled')->name('jobs.view-cancelled');
Route::get('/view-unassigned', 'jobsController@getUnassigned')->name('jobs.view-unassigned');
Route::get('/view-completed', 'jobsController@getCompleted')->name('jobs.view-completed');
Route::get('/view-onhold', 'jobsController@getOnHold')->name('jobs.view-nohold');
Route::get('/view-scheduled', 'jobsController@getScheduled')->name('jobs.view-scheduled');
Route::get('/all-jobs', 'jobsController@getAllJobs')->name('jobs.all-jobs');
Route::get('/jobs-report', 'jobsController@getJobsReport')->name('jobs.jobs-report');
Route::post('/jobs-report-range', 'jobsController@getJobsReportRange')->name('jobs.jobs-report-range');
Route::get('/today-jobs', 'jobsController@getTodayJobs')->name('jobs.today-jobs');
// Route::post('seller/update_store_slider','API\SellerController@updateSlider');
Route::get('/assigned-job-view/{order_id}','jobsController@viewAssginedJobs')->name('jobs.assigned-job-view');
Route::get('/schedule-details/{order_id}','jobsController@getScheduleDetails')->name('jobs.schedule-details');
Route::post('/unassigned-job-submit','jobsController@unassignedJobSubmit')->name('unassigned-job-submit');
//Panic
Route::get('/panic-reported', 'panicController@getPanicReported')->name('panic.panic-reported');
Route::get('/panic-resolved', 'panicController@getPanicResolved')->name('panic.panic-resolved');
Route::resource('panic','panicController');

Route::get('/request/orders', 'RequestController@index')->name('admin.request.order');

Route::get('/payment', 'PaymentController@index')->name('admin.payment');
Route::post('/payment/{id}', 'PaymentController@update')->name('admin.payment.update');

Route::get('/fmc','notificationController@sendNotification');
Route::get('/send-notification/{test}/{id}','notificationController@checkSendNotification')->name('send-notification');

Route::get('/user/notf/show', 'notificationController@user_notf_show')->name('user-notf-show');
Route::get('/user/final/approval/show', 'notificationController@final_approval_notf_show')->name('final-approval-notf-show');
Route::get('/user/panic/show', 'notificationController@panic_notf_show')->name('panic-notf-show');

Route::resource('share','ShareController');

Route::post('/save-token', 'notificationController@saveToken')->name('save-token');

/* BULK MESSAGE */
Route::get('/bulk/message/', 'BulkMessageController@index')->name('bulk.message');
Route::post('/bulk/message/send', 'BulkMessageController@send')->name('bulk.message.send');
Route::post('/bulk/message/service', 'BulkMessageController@service')->name('bulk.message.with.service');

Route::post('get-user-by-role','BulkMessageController@getUserByRole');

/* SCHEDULE TIME COUNT */
Route::get('/schedule', 'ScheduleController@index')->name('schedule.index');
Route::post('/schedule/{id}', 'ScheduleController@update')->name('schedule.update');

Route::get('/no-service-charges', 'servicesController@noServiceCharges')->name('no.service.charges');
Route::post('/no-service-charges', 'servicesController@noServiceChargesUpdate')->name('no.service.charges.update');

//Update Status
Route::post('/job/status/updated/{id}', 'jobsController@statusUpdate')->name('update.status');

app/Http/Controllers/customerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\territory;
use App\personInfo;
use App\Orders;
use DB;
use Validator;
use Auth;

class customerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 

    public function index()
    {
        //$data = personInfo::select('*')->where('r_id',3)->get();

         $data = DB::table('per_info')->join('city', 'per_info.city_id', '=', 'city.city_id')
                ->join('territory', 'territory.terr_id', '=', 'per_info.terr_id')
                ->select('per_info.regId', 'per_info.fullName', 'per_info.nickName', 'per_info.phn_no', 'territory.name as area','per_info.pri_add','per_info.cnic', 'per_info.email', 'per_info.age', 'per_info.image','per_info.created_at as register_date', 'city.name as city')
                ->where([
                    ['r_id', 3],
                    ])
                ->get();
            
        if (count($data) != 0) {
            
            foreach ($data as $customer) {
                $count = DB::table('orders')
                            ->select('order_id')
                            ->where('orders.regId',$customer->regId)
                            ->count();
            $customer->orders_count = $count;
            }

                      
        }
        // dump($data);die();
           
        
 

                 return view('customer.index', compact('data'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = personInfo::find($id);
        $data->completed_order = Orders::where('status', 'Completed')
                                    ->where('regId', $id)
                                    ->count();
        $data->completed_not_order = Orders::where('status', '!=' ,'Completed')
                                        ->where('regId', $id)
                                        ->count();
        $data->amount_recieved = Orders::where('regId', $id)
                                    ->where('amount_received', '!=', null)
                                    ->sum('amount_received');
        $data->amount_not_recieved = Orders::where('status', '!=' ,'Completed')
                                    ->where('regId', $id)
                                    ->sum('total_amount');
        $data->total_amount = Orders::where('regId', $id)
                                ->sum('total_amount');
        return view('customer.view', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">My Customers</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a>
                    </li>
                    <li class="breadcrumb-item active">Customers
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
@if($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{$message}}</p>
</div>
@endif
<div class="row">
    <div id="recent-sales" class="col-12 col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Customers List</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
            </div>
            <div class="card-content mt-1">
                <div class="table-responsive" style="padding: 2%;">
                    <table class="table table-striped table-bordered zero-configuration">
                        <thead>
                            <tr>
                                <th>Customer ID</th>
                                <th>Full Name</th>
                                <th>Registered Mobile number</th>
                                <th>Completed order</th>
                                <th>Area</th>
                                <th>City</th>
                                <!-- 	<th>Action</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $customers)
                            <tr>
                                <td class="text-truncate">{{$customers->regId}}</td>
                                <td class="text-truncate"><a href="{{route('customer.show', $customers->regId)}}">{{$customers->fullName}}</a></td>
                                <td class="text-truncate">{{$customers->phn_no}}</td>
                                <td class="text-truncate">{{$customers->orders_count}}</td>
                                <td class="text-truncate">{{$customers->area}}</td>
                                <td class="text-truncate">{{$customers->city}}</td>
                                <!-- <td>
                                    <div class="buy-now"><a href="{{ route('customer.edit', $customers->regId) }}" class="btn btn-info btn-glow round px-1" style="  padding: 0.5rem 0.5rem; font-size: 0.5rem;">Edit Profile</a></div>
                                    </td> -->
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
@endpush

resources/views/customer/view.blade.php
@extends('layouts.admin')
@section('content')
@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="content-body">
    <!-- users view start -->
    <section class="users-view">
        <!-- users view media object start -->
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="media">
                                <a class="mr-1" href="#">
                                    <img src="{{$data->image}}" alt="users view avatar" class="users-avatar-shadow rounded-circle" height="64" width="64">
                                </a>
                                <div class="media-body pt-25">
                                    <h4 class="media-heading"><span class="users-view-name">{{$data->fullName}} </span></h4>
                                    <span>ID:</span>
                                    <span class="users-view-id">{{$data->regId}}</span><br>
                                    <span>PHONE:</span>
                                    <span class="users-view-id">{{$data->phn_no}}</span>
                                </div>
                            </div>
                            <span class="badge badge-info badge-md mt-1">{{$data->city->name}} | {{$data->territory->name}}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card pull-up mb-1">
                            <div class="card-content">
                                <div class="card-body">
                                    <div class="media d-flex">
                                        <div class="media-body text-left">
                                            <h6 class="text-muted">Total Order</h6>
                                            <h3>{{ count($data->customer_order) }}</h3>
                                        </div>
                                        <div class="align-self-center">
                                            <i class="icon-check success font-large-2 float-right"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card pull-up mb-1">
                            <div class="card-content">
                                <div class="card-body">
                                    <div class="media d-flex">
                                        <div class="media-body text-left">
                                            <h6 class="text-muted">Order Completed</h6>
                                            <h3>{{ $data->completed_order }}</h3>
                                        </div>
                                        <div class="align-self-center">
                                            <i class="icon-check success font-large-2 float-right"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card pull-up mb-1">
                            <div class="card-content">
                                <div class="card-body">
                                    <div class="media d-flex">
                                        <div class="media-body text-left">
                                            <h6 class="text-muted">Order Not Completed</h6>
                                            <h3>{{ $data->completed_not_order }}</h3>
                                        </div>
                                        <div class="align-self-center">
                                            <i class="icon-check success font-large-2 float-right"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card pull-up mb-1">
                            <div class="card-content">
                                <div class="card-body">
                                    <div class="media d-flex">
                                        <div class="media-body text-left">
                                            <h6 class="text-muted">Total Amount </h6>
                                            <h3>Rs. {{$data->total_amount}}</h3>
                                        </div>
                                        <div class="align-self-center">
                                            <i class="icon-credit-card success font-large-2 float-right"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card pull-up mb-1">
                            <div class="card-content">
                                <div class="card-body">
                                    <div class="media d-flex">
                                        <div class="media-body text-left">
                                            <h6 class="text-muted">Amount Paid </h6>
                                            <h3>Rs. {{$data->amount_recieved}}</h3>
                                        </div>
                                        <div class="align-self-center">
                                            <i class="icon-credit-card success font-large-2 float-right"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-md-4">
                        <div class="card pull-up">
                            <div class="card-content">
                                <div class="card-body">
                                    <div class="media d-flex">
                                        <div class="media-body text-left">
                                            <h6 class="text-muted">Amount Not Paid </h6>
                                            <h3>Rs. {{$data->amount_not_recieved}}</h3>
                                        </div>
                                        <div class="align-self-center">
                                            <i class="icon-credit-card success font-large-2 float-right"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <!-- users view media object ends -->
        <!-- users view card data start -->
        <div class="row">
            <div id="recent-sales" class="col-12 col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="content-header-title mb-0 d-inline-block">Order List</h3>
                    </div>
                    <div class="card-content">
                        <div class="table-responsive pt-0" style="padding: 2%;">
                            <table class="table table-striped table-bordered zero-configuration">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Service</th>
                                        <th>Total Amount</th>
                                        <th>Order Status</th>
                                        <th>Created Date</th>
                                        <th>Assigned To</th>
                                        <th>Payment Method</th>
                                        <th>Amount Received</th>
                                        <th>Address</th>
                                        <th>Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($data->customer_order as $orders)
                                    <tr>
                                        <td class="text-truncate">{{$orders->order_id}}</td>
                                        <td class="text-truncate">
                                          <span class="badge badge-info">{{$orders->service->name}}</span>
                                        </td>
                                        <td class="text-truncate">Rs. {{$orders->total_amount}}</td>
                                        <td class="text-truncate"><span class="badge badge-info">{{$orders->status}}</span></td>
                                        <td class="text-truncate">{{date('l jS \of F Y h:i:s A', strtotime($orders->create_at))}}</td>
                                        <td class="text-truncate">
                                            @if($orders->assign_to != null)
                                            <span class="badge badge-success">{{$orders->assign_person->fullName}}</span>
                                            @else
                                            <span class="badge badge-danger">No Assigned</span>
                                            @endif
                                        </td>
                                        <td class="text-truncate">{{$orders->payment_method}}</td>
                                        <td class="text-truncate">
                                            @if($orders->amount_received != null)
                                            <span class="badge badge-success">Rs. {{$orders->amount_received}}</span>
                                            @else
                                            <span class="badge badge-danger">No Received</span>
                                            @endif
                                        </td>
                                        <td class="text-truncate">{{$orders->full_address}}</td>
                                        <td>
                                            <div class="buy-now">
                                                <a href="{{ route('jobs.show', $orders->order_id) }}" class="btn btn-sm btn-outline-info round" >View Details</a>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- users view card details ends -->
    </section>
    <!-- users view ends -->
</div>
@endsection
@push('scripts')
<script>
    
</script>
@endpush