routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('auth.login');
});







Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Agent
Route::resource('agent','agentController');
//customer
Route::resource('customer','customerController');
//Supervisor
Route::resource('supervisor','supervisorController');
//City
Route::resource('city','cityController');
//Slider
Route::get('slider','SliderController@create')->name('slider.create');
Route::get('slider/all','SliderController@index')->name('slider.index');
Route::post('slider','SliderController@store')->name('slider.store');
Route::get('slider/{id}','SliderController@edit')->name('slider.edit');
Route::post('slider/{id}','SliderController@update')->name('slider.update');

//area
Route::resource('area','areaController');
//notification
Route::resource('notification','notificationController');
//services
Route::resource('services','servicesController');
//Sub services
Route::resource('subservices','subservicesController');
//FAQS
Route::resource('faqs','FaqsController');

Route::get('supervisor/assigned-kamay-to-supervisor/{id}','supervisorController@getAssignedKamayToSupervisor')->name('supervisor.assigned-kamay-to-supervisor');

//Badges
Route::resource('badges','BadgeController');

//Person Badges
Route::resource('assign-badges','PerBadgeController');
Route::post('get-badges-by-user','PerBadgeController@getBadgesByUser');

//Kamay Worker
Route::resource('kama','kamaController');
Route::get('/worker-growth-potential', 'kamaGrowthController@kamaGrowth')->name('worker-growth-potential');
Route::get('/kamayview', 'kamaController@kamayView')->name('kamayview');
Route::get('/final-approval-kamay', 'kamaController@getFinalApprovalKamay')->name('final-approval-kamay');
Route::get('/assigned-kamay', 'kamaController@getAssignedKamay')->name('assigned-kamay');
Route::get('/kamayrequest', 'kamaController@kamayRequest')->name('kamayrequest');
Route::post('get-area-by-city','kamaController@getArea');
Route::post('get-area-by-cityname','kamaController@getAreaByCityName');
Route::post('/assign-supervisor','kamaController@assignSupervisor')->name('assign-supervisor');
Route::post('/final-approval/{id}','kamaController@finalApproval')->name('final-approval');
Route::get('/view-approved-worker', 'kamaController@getApprovedWorker')->name('view-approved-worker');
Route::get('/assigned-supervisor-list/{kama_id}','kamaController@supervisorAssignedList')->name('assigned-supervisor-list');

//Jobs
Route::resource('jobs','jobsController');
Route::get('/view-inprogress', 'jobsController@getInprogress')->name('jobs.view-inprogress');
Route::get('/view-cancelled', 'jobsController@getCancelled')->name('jobs.view-cancelled');
Route::get('/view-unassigned', 'jobsController@getUnassigned')->name('jobs.view-unassigned');
Route::get('/view-completed', 'jobsController@getCompleted')->name('jobs.view-completed');
Route::get('/view-onhold', 'jobsController@getOnHold')->name('jobs.view-nohold');
Route::get('/view-scheduled', 'jobsController@getScheduled')->name('jobs.view-scheduled');
Route::get('/all-jobs', 'jobsController@getAllJobs')->name('jobs.all-jobs');
Route::get('/jobs-report', 'jobsController@getJobsReport')->name('jobs.jobs-report');
Route::post('/jobs-report-range', 'jobsController@getJobsReportRange')->name('jobs.jobs-report-range');
Route::get('/today-jobs', 'jobsController@getTodayJobs')->name('jobs.today-jobs');
// Route::post('seller/update_store_slider','API\SellerController@updateSlider');
Route::get('/assigned-job-view/{order_id}','jobsController@viewAssginedJobs')->name('jobs.assigned-job-view');
Route::get('/schedule-details/{order_id}','jobsController@getScheduleDetails')->name('jobs.schedule-details');
Route::post('/unassigned-job-submit','jobsController@unassignedJobSubmit')->name('unassigned-job-submit');
//Panic
Route::get('/panic-reported', 'panicController@getPanicReported')->name('panic.panic-reported');
Route::get('/panic-resolved', 'panicController@getPanicResolved')->name('panic.panic-resolved');
Route::resource('panic','panicController');

Route::get('/request/orders', 'RequestController@index')->name('admin.request.order');

Route::get('/payment', 'PaymentController@index')->name('admin.payment');
Route::post('/payment/{id}', 'PaymentController@update')->name('admin.payment.update');

Route::get('/fmc','notificationController@sendNotification');
Route::get('/send-notification/{test}/{id}','notificationController@checkSendNotification')->name('send-notification');

Route::get('/user/notf/show', 'notificationController@user_notf_show')->name('user-notf-show');
Route::get('/user/final/approval/show', 'notificationController@final_approval_notf_show')->name('final-approval-notf-show');
Route::get('/user/panic/show', 'notificationController@panic_notf_show')->name('panic-notf-show');

Route::resource('share','ShareController');

Route::post('/save-token', 'notificationController@saveToken')->name('save-token');

/* BULK MESSAGE */
Route::get('/bulk/message/', 'BulkMessageController@index')->name('bulk.message');
Route::post('/bulk/message/send', 'BulkMessageController@send')->name('bulk.message.send');
Route::post('/bulk/message/service', 'BulkMessageController@service')->name('bulk.message.with.service');

Route::post('get-user-by-role','BulkMessageController@getUserByRole');

/* SCHEDULE TIME COUNT */
Route::get('/schedule', 'ScheduleController@index')->name('schedule.index');
Route::post('/schedule/{id}', 'ScheduleController@update')->name('schedule.update');

Route::get('/no-service-charges', 'servicesController@noServiceCharges')->name('no.service.charges');
Route::post('/no-service-charges', 'servicesController@noServiceChargesUpdate')->name('no.service.charges.update');

//Update Status
Route::post('/job/status/updated/{id}', 'jobsController@statusUpdate')->name('update.status');

resources/views/service_share/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">Add Shares</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Add Shares</li>
                </ol>
            </div>
        </div>
    </div>
</div>
@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="content-body">
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="basic-layout-form">Shares Details</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <form class="form" method="POST" enctype="multipart/form-data">
                                @csrf   
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="label">Shares Label <span>*</span></label>
                                                <input type="text" id="label" class="form-control" placeholder="Shares Label" name="label" required="required">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="projectinput1">Select Status <span>*</span></label>
                                                <select name="status" id="status" class="form-control" required>
                                                    <option value="">Select Status</option>
                                                    <option value="1">Active</option>
                                                    <option value="0">Deactive</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions text-right">
                                    <button type="submit" class="btn btn-primary">
                                    <i class="la la-check-square-o"></i> Save
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
               <div class="card">
                  <div class="card-header">
                     <h4 class="card-title" id="basic-layout-colored-form-control">Information</h4>
                     <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                     <div class="heading-elements">
                        <ul class="list-inline mb-0">
                           <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                           <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                           <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                           <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="card-content collapse show">
                     <div class="card-body pt-0" id="error_box">
                        @if($errors->any())
                        <div class="alert alert-danger">
                           <ul>
                              @foreach($errors->all() as $error)
                              <li>{{ $error }}</li>
                              @endforeach
                           </ul>
                        </div>
                        @endif
                        @if (\Session::has('error'))
                        <div class="alert alert-danger">
                           <ul>
                              <li>{!! \Session::get('error') !!}</li>
                           </ul>
                        </div>
                        @endif
                        @if (\Session::has('success'))
                        <div class="alert alert-success">
                           <ul>
                              <li>{!! \Session::get('success') !!}</li>
                           </ul>
                        </div>
                        @endif
                     </div>
                  </div>
               </div>
            </div>
        </div>
    </section>
</div>
@stop
@section('script')
<script>
    $('.form').on('submit', function(event){
        event.preventDefault();
        var formData = new FormData(this);
        _ajax.postFormData("{{route('share.store')}}",formData , function(response) {
            if(response.status){
                $('#error_box').html('');
                $('#error_box').html('<div class="alert alert-success"><ul><li>'+response.message+'</li></ul></div>');
                $('.form').trigger("reset");
            }else{
                console.log(response);
                var errorString = '<div class="alert alert-danger"><ul>';
                $.each( response.data, function( key, value) {
                    errorString += '<li>' + value + '</li>';
                });
                errorString += '</ul></div>';
                $('#error_box').html('');
                $('#error_box').html(errorString);
            }
            window.scrollTo(0, 0);
        })
    });
</script>
@endsection

resources/views/service_share/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">Edit Share</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Edit Share</li>
                </ol>
            </div>
        </div>
    </div>
</div>
@if($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
<div class="content-body">
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="basic-layout-form">Shares Update</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                <li><a data-action="close"><i class="ft-x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <form class="form" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PATCH')  
                                <div class="form-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="label">Shares Label <span>*</span></label>
                                                <input type="text" id="label" class="form-control" placeholder="Shares Label" value="{{$data->label}}" name="label" required="required">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="projectinput1">Select Status <span>*</span></label>
                                                <select name="status" id="status" class="form-control" required>
                                                    <option value="">Select Status</option>
                                                    <option value="1" {{$data->status == 1 ? 'selected' : ''}}>Active</option>
                                                    <option value="0" {{$data->status == 0 ? 'selected' : ''}}>Deactive</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions text-right">
                                    <button type="submit" class="btn btn-primary">
                                    <i class="la la-check-square-o"></i> Update
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
               <div class="card">
                  <div class="card-header">
                     <h4 class="card-title" id="basic-layout-colored-form-control">Information</h4>
                     <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                     <div class="heading-elements">
                        <ul class="list-inline mb-0">
                           <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                           <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                           <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                           <li><a data-action="close"><i class="ft-x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="card-content collapse show">
                     <div class="card-body pt-0" id="error_box">
                        @if($errors->any())
                        <div class="alert alert-danger">
                           <ul>
                              @foreach($errors->all() as $error)
                              <li>{{ $error }}</li>
                              @endforeach
                           </ul>
                        </div>
                        @endif
                        @if (\Session::has('error'))
                        <div class="alert alert-danger">
                           <ul>
                              <li>{!! \Session::get('error') !!}</li>
                           </ul>
                        </div>
                        @endif
                        @if (\Session::has('success'))
                        <div class="alert alert-success">
                           <ul>
                              <li>{!! \Session::get('success') !!}</li>
                           </ul>
                        </div>
                        @endif
                     </div>
                  </div>
               </div>
            </div>
        </div>
    </section>
</div>
@stop
@section('script')
<script>
    $('.form').on('submit', function(event){
        event.preventDefault();
        var formData = new FormData(this);
        _ajax.postFormData("{{route('share.update',$data->id)}}",formData , function(response) {
            if(response.status){
                $('#error_box').html('');
                $('#error_box').html('<div class="alert alert-success"><ul><li>'+response.message+'</li></ul></div>');
                $('.form').trigger("reset");
            }else{
                console.log(response);
                var errorString = '<div class="alert alert-danger"><ul>';
                $.each( response.data, function( key, value) {
                    errorString += '<li>' + value + '</li>';
                });
                errorString += '</ul></div>';
                $('#error_box').html('');
                $('#error_box').html(errorString);
            }
            window.scrollTo(0, 0);
        })
    });
</script>
@endsection

resources/views/service_share/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header row">
    <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">List Shares</h3>
        <div class="row breadcrumbs-top d-inline-block">
            <div class="breadcrumb-wrapper col-12">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a>
                    </li>
                    <li class="breadcrumb-item active">Shares
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
@if($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{$message}}</p>
</div>
@endif
<div class="row">
    <div id="recent-sales" class="col-12 col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title" id="basic-layout-form">Sub Services Form</h4>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                        <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                        <li><a data-action="close"><i class="ft-x"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-content">
                <div class="table-responsive" style="padding: 2%;">
                    <table class="table table-striped table-bordered zero-configuration">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Label</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $datas)
                            <tr>
                                <td class="text-truncate">{{$datas->id}}</td>
                                <td class="text-truncate">{{$datas->label}}</td>
                                <td class="text-truncate">
                                  @if($datas->status == 1)
                                    <button class="btn btn-info btn-sm">Active</button>
                                  @else
                                    <button class="btn btn-info btn-sm">Deactive</button>
                                  @endif
                                </td>
                                <td align="center">
                                    <div class="fonticon-wrap">
                                        <a href="{{ route('share.edit', $datas->id) }}" class="btn btn-sm btn-primary"><i class="ft-edit"></i></a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
@endpush